### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by codemuscles** [codemuscles/Cowls-Community#14]
Make Login Page using HTML,CSS&Javascript

**Comment by GeorgeET15** [comment]
Hi can you assign this to me

**Comment by Esha-in-arena** [comment]
@codemuscles i can do it. assign it to me

**Comment by Sparsh47** [comment]
Can you assign this to me?

**Comment by mundadapurva** [comment]
@codemuscles I have got a lot of experience in building login pages, can you assign this to me?

**Comment by codemuscles** [comment]
@mundadapurva @Esha-01 @Sparsh47 You all go for it😃. Simply fork this repo and commit changes. And send pull request. The best page **will be committed** to the main repo. Now I am closing this issue.
