### ISSUE TITLE
insertition sort

### ISSUE THREAD

**Issue by kdg9546** [codemuscles/Cowls-Community#8]
I can write code for Insertion Sort in c language

**Comment by ShahzaibJutt** [comment]
Assign this to me.

**Comment by constantinosgeorgiou** [comment]
I can create a PR for this issue. Please assign it to me

**Comment by codemuscles** [comment]
@constantinosgeorgiou we already have code for it in C language. Write code in other Language. And submit pull request.

**Comment by Pratyu2003** [comment]
Hey @codemuscles, I can write code for Insertion Sort in Java. Can you assign me this issue?

**Comment by codemuscles** [comment]
@Pratyu2003 Go for it
